"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

# --- Application Details ---
APP_NAME = "promera_ai"
APP_SCRIPT = "promera_ai.py"
VERSION = "1.0.0"

# --- Icon ---
# Create or place your icon file in the same directory and name it 'app_icon.icns'
# You can convert a PNG to ICNS using online tools or macOS's built-in 'iconutil'
ICON_FILE = "app_icon.icns"

# --- py2app Options ---
OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'requests',
        'reportlab',
        'docx',
        'pyaudio',
        'numpy',
        'metaphone',
        'lemminflect',
        'huggingface_hub'
    ],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "A comprehensive Text Processing GUI application.",
        'CFBundleIdentifier': "com.yourdomain.promeraai",
        'CFBundleVersion': VERSION,
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': u"Copyright © 2025, Your Name Here. All Rights Reserved."
    },
}

# Add icon to options if it exists
if os.path.exists(ICON_FILE):
    OPTIONS['iconfile'] = ICON_FILE

# --- Setup Configuration ---
setup(
    name=APP_NAME,
    app=[APP_SCRIPT],
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)